
declare global {
  var ABC:any;
}
export const ABC: any = abcjs;
// import { MidiService } from '@components/guitar/midi.service';
// import { GuitarService } from '@components/guitar/guitar.service';
@NgModule({
  declarations: [
    AppComponent,
    SongComponent,
    HomeComponent,
    BrowseComponent,
    TransportComponent,
    MetroComponent,
    TestpageComponent,
    GuitarComponent,
    TabParserComponent,
    ChordsFromYoutubeComponent,
    FifthCircleComponent,
    MidiChordDetectSimpleComponent,
    LearnFifthsComponent,
    PianoComponent,
    CreateFifthsExerciseComponent,
    MetroPageComponent,
    NavbarComponent,
    YoutubeAudioComponent,
    EditorComponent,
    MidiChordDetectAbcComponent,
    ExerciceRythmComponent,
    DraftComponent,
    PageFifthCircleComponent,
    PageGeneratorComponent,
    TemplateViewerComponent,
    ResultsComponent,
    ChordComponent,
    CountdownComponent,
    NotesComponent,
    MixedTemplateComponent,
    MidiSelectorComponent,
    InstrLvl1Component,
    PageExerciseSelectionComponent,
    AbcCheckerComponent,
    AbcCheckerFullScoreComponent,
    AbcHearingComponent,
    DicoComponent,
    PianoMiniComponent,
    ChordsBrowseComponent,
    PageArtistComponent,
    PageAlbumComponent,
    PageStyleComponent,
    PageAuthorComponent,
    PageKeyComponent,
    FretboardComponent,
    FretboardDiamondComponent,
    PianoDiamondComponent,
    ScaleSelectorComponent,
    TonalityButtonComponent,
    BraidComponent,
    MidiControlSelectorComponent,
    ResetPasswordComponent,
    StatsComponent,
    DonateComponent,
    ChordstripComponent,
    StoreComponent,
    MidiChordDisplayComponent,
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    AppRoutingModule,
    FormsModule,
    CookieModule.forRoot(),
  providers: [
    Songmodel,
    SongInfo,
    Statsmodel,
    StorageService, 
    ExoGenService,
    SynthService,
    ExerciseResultsService,
    DisplayService,
    SelectionModel,
    ConfigModel,
    TransportService,
    ParsingService,
    MidiService,
    MusicUtilsService,
    UserModel,
    YoutubeService,
    AudioPlayer,
    ChordDetectService,
    SoundfontService,
    ExerciseModel,
    DiscogsService,
    SpotifyService,
    CurTonalityModel,
    CurChordModel
    ],
  bootstrap: [AppComponent],
  // entryComponents: [ChordComponent]
})
export class AppModule  { }
