#!/bin/bash

usage="\n\n $(basename "$0") [-h] [-c -bars -y -f -n -l -d] 
 
Recupere et analyse le contenu audio d'une video youtube.
Le programme utilise sonic-annotator pour les différents algorithmes.


Options:
	-y=  télécharge le son du lien youtube indiqué

	-f= applique l'alorithme sur le fichier mp3 fournit.
		Si un lien youtube est fournit et que cette option est fournie,
		le fichier mp3 téléchargé prends le nom (et l'emplacement) fourni
		par ce paramètre.
	
	-n= donne le nom fournit en paramètre au fichier sonore récupéré de 
		youtube.

	-novaxe parametre special pour l'application novaxe

	-c  applique l'algorithme de déchiffrage des accords.

    -a  analyse avec harmtrace.

	-bars applique l'algorithme de marquage des premiers temps de mesure.

	-l renvoie les probabilités que la prédiction soit exacte.

	-h  montrer ce texte

	
"

if [[ -z "$@" ]]; then
	printf "$usage"
	exit 1
fi
for i in "$@"
do
case $i in
    -f=*|--file=*)
    FILE="${i#*=}"
    shift # past argument=value
    ;;
    -bars|--firstBeat)
    FIRSTBEAT=YES
    shift # past argument=value
    ;;
    -c|--chords)
    CHORDS=YES
    shift # past argument=value
    ;;
    -lc)
    LIKELYHOOD=YES
    CHORDS=YES
    shift # past argument=value
    ;;
    -cl)
    LIKELYHOOD=YES
    CHORDS=YES
    shift # past argument=value
    ;;
    -l|--likely)
    LIKELYHOOD=YES
    shift # past argument=value
    ;;
    -y=*|--youtube=*)
    YOUTUBE="${i#*=}"
    DOWNLOAD=YES
    shift # past argument=value
    ;;
    -n=*|--name=*)
NAME="${i#*=}"
    shift # past argument=value
    ;;
    -s)
SEGMENT=YES
    shift # past argument=value
    ;;
    -a)
ANALYSE=YES
    shift # past argument=value
    ;;
    -novaxe)
CHORDS=YES
LIKELYHOOD=YES
FIRSTBEAT=YES
    shift # past argument with no value
    ;;
    --default)
DEFAULT=YES
    shift # past argument with no value
    ;;
    *|-h)
printf "$usage"
exit 1
            # unknown option
            ;;
        esac
    done

    if [[ -z $FILE ]] && [[ -z $NAME ]]; then
       FILE="temp.mp3"
       NAME="${FILE%.*}"
   fi
   if [[ -z $NAME ]] && [[ -n $FILE ]]; then
       NAME="${FILE%.*}"
   fi
   if [[ -n $NAME ]] && [[ -z $FILE ]]; then
       FILE=${NAME}.mp3
   fi

   if [[ -n $YOUTUBE ]]; then
    printf "\n\n------------Downloading------------\n\n"
    ./youtube-dl -x --audio-format mp3 -o "${NAME}.%(ext)s" $YOUTUBE


fi

cachePath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cachePath="${cachePath}/getChordCache"

CHAIN=""
if [[ -n $CHORDS ]]; then
	CHAIN="${CHAIN} -t ${cachePath}/chords.txt"
    printf "\n\nWill check for chords\n\n"
fi
if [[ -n $LIKELYHOOD ]]; then
	CHAIN="${CHAIN} -t ${cachePath}/likely.txt"
    printf "\n\nWill check likelyhood of chords\n\n"
fi
if [[ -n $FIRSTBEAT ]]; then
	CHAIN="${CHAIN} -t ${cachePath}/measures.txt"
    printf "\n\nWill check for beats\n\n"
fi
if [[ -n $SEGMENT ]]; then
    CHAIN="${CHAIN} -t ${cachePath}/segmentino.txt"
    printf "\n\nWill check for segmentation\n\n"
fi


printf "\n\n------------Analyse audio------------\n\n"
sonic-annotator ${CHAIN} -w jams ${FILE} --jams-force



if [[ -n $ANALYSE ]]; then
    printf "\n\n------------Analyse accords------------\n\n"
    ${cachePath}/postGetChord $(pwd)/temp.json
    cat $(pwd)/graph.txt
    # stack exec harmtrace parse -- --grammar=jazz --chords="G:maj $(cat graph.txt)" --print
    # stack exec harmtrace parse -- --grammar=jazz --chords="G:maj $(cat graph.txt)" 
fi
