#! /usr/bin/node

var args = process.argv.slice(2);
var fs = require('fs');
var parsedJson = require(args[0]);


//we get the data from getChord Output
for( var i = 0; i < parsedJson.annotations.length; i++ ){
	if(parsedJson.annotations[i].annotation_metadata.annotator.output_id == 'loglikelihood'){
		var dataProbas = parsedJson.annotations[i].data;
	}else if( parsedJson.annotations[i].annotation_metadata.annotator.output_id == 'simplechord'){
		var dataChords = parsedJson.annotations[i].data;
	}else if( parsedJson.annotations[i].annotation_metadata.annotator.output_id == 'bars'){
		var dataBars = parsedJson.annotations[i].data;
	}
}

if(dataProbas){

	//we get the probas at chords positions
	var obj;
	for(var i = 0; i < dataChords.length ; i++){

		obj = dataProbas.filter(function ( obj ) {
			return obj.time === dataChords[i].time;
		})[0];
		dataChords[i].confidence = obj.value;
	}
}


function getClosestChord ( time, chords ) {
	
	var index = 0;
	var tempValue = Math.abs( time - chords[0].time );

	for ( var i = 1 ; i < chords.length ; i++ ) {

		if ( Math.abs( chords[i].time - time ) < tempValue ){

			tempValue = Math.abs( chords[i].time - time ); 
			index = i;
		}
	}
	return index;
}

function closest( chords, measures ) {
	var closestChord = {};
	var chaine = "";

	for( var i = 0 ; i < measures.length ; i++ ){
		closestChord = getClosestChord(measures[i].time, chords );
		measures[i].chord = chords[ closestChord ].value;
		if(chords[closestChord].value != "N") chaine += chords[closestChord].value+";1 "
		measures[i].chordTime= chords[ closestChord ].time;
		measures[i].confidence = chords[ closestChord ].confidence;
	}
	return chaine;
}
if(dataChords && dataBars){

	var chaine = closest( dataChords, dataBars );
	fs.writeFile('post.json', JSON.stringify(dataBars,null,"\t"), 'utf8', function(){console.log('Wrote post treatment data.')});
	fs.writeFile('graph.txt', chaine, 'utf8', function(){console.log('Wrote chords for graph')});
}else{
	console.log( 'Missing chords data or bars data !! ');
}
